// Auto-generated (partially) by scripts/generate-from-checkpoint.mjs
// Supplemented with USA Coin Book data. Hand-written entries preserved where scrape missing.

export interface CoinEducation {
  description?: string
  designer?: string
  composition?: string
  diameter?: string
  weight?: string
  edge?: string
  imageUrl?: string
  mintage?: string
  keyDates?: string[]
  funFact?: string
}

export const COIN_EDUCATION: Record<string, CoinEducation> = {
  'liberty-cap-half-cent': {
    description: "Coin Value Price Chart for Liberty Cap Half Cents 1/2C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Liberty Cap Half Cents are worth. Buy & Sell. Coins for sale for Liberty Cap type Half Cents items.",
    designer: "Robert Scot",
    composition: "100% Copper",
    diameter: "23.5 mm",
    weight: "6.74 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/liberty-cap-half-cent-facing-left.webp",
    keyDates: [
      "1793 Liberty Cap Half Cents : Head Facing Left",
      "1795 Liberty Cap Half Cents : Lettered Edge with Pole",
      "1796 Liberty Cap Half Cents : With Pole",
    ],
  },
  'draped-bust-half-cent': {
    description: "Coin Value Price Chart for Draped Bust Half Cents 1/2C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Draped Bust Half Cents are worth. Buy & Sell. Coins for sale for Draped Bust type Half Cents items.",
    designer: "Robert Scot",
    composition: "100% Copper",
    diameter: "23.5 mm",
    weight: "5.44 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/draped-bust-half-cent.webp",
    keyDates: [
      "1802 Draped Bust Half Cents : 2 Over 0 - Reverse of 1802",
    ],
  },
  'classic-head-half-cent': {
    description: "Coin Value Price Chart for Classic Head Half Cents 1/2C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Classic Head Half Cents are worth. Buy & Sell. Coins for sale for Classic Head type Half Cents items.",
    designer: "John Reich",
    composition: "100% Copper",
    diameter: "23.5 mm",
    weight: "5.44 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/classic-head-half-cent.webp",
    keyDates: [
      "1831 Classic Head Half Cents : Original",
    ],
  },
  'braided-hair-half-cent': {
    description: "Coin Value Price Chart for Braided Hair Half Cents 1/2C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Braided Hair Half Cents are worth. Buy & Sell. Coins for sale for Braided Hair type Half Cents items.",
    designer: "Christian Gobrecht",
    composition: "100% Copper",
    diameter: "23 mm",
    weight: "5.44 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/braided-hair-half-cent.webp",
    keyDates: [
      "1849 Braided Hair Half Cents : Large Date",
      "1850 Braided Hair Half Cents",
      "1856 Braided Hair Half Cents",
      "1857 Braided Hair Half Cents",
    ],
  },
  'flowing-hair-cent': {
    description: "Coin Value Price Chart for Flowing Hair Large Cents 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Flowing Hair Large Cents are worth. Buy & Sell. Coins for sale for Flowing Hair type Large Cents items.",
    designer: "Henry Voigt",
    composition: "100% Copper",
    diameter: "27 mm",
    weight: "13.48 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/flowing-hair-large-cent-chain.webp",
    keyDates: [
      "1793 Flowing Hair Large Cents : All Varieties",
      "1793 Flowing Hair Large Cents : Strawberry Leaf",
    ],
  },
  'liberty-cap-cent': {
    description: "Coin Value Price Chart for Liberty Cap Large Cents 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Liberty Cap Large Cents are worth. Buy & Sell. Coins for sale for Liberty Cap type Large Cents items.",
    designer: "Joseph Wright",
    composition: "100% Copper",
    diameter: "29 mm",
    weight: "13.48 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/liberty-cap-large-cent.webp",
    keyDates: [
      "1793 Liberty Cap Large Cents",
      "1795 Liberty Cap Large Cents : Lettered Edge - One Cent High in Wreath",
      "1795 Liberty Cap Large Cents : Reeded Edge",
      "1795 Liberty Cap Large Cents : Jefferson Head - Lettered Edge",
    ],
  },
  'draped-bust-cent': {
    description: "Coin Value Price Chart for Draped Bust Large Cents 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Draped Bust Large Cents are worth. Buy & Sell. Coins for sale for Draped Bust type Large Cents items.",
    designer: "Robert Scot",
    composition: "100% Copper",
    diameter: "29 mm",
    weight: "10.89 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/draped-bust-large-cent.webp",
    keyDates: [
      "1796 Draped Bust Large Cents : Stemless Wreath Reverse",
      "1799 Draped Bust Large Cents : Normal Date",
    ],
  },
  'classic-head-cent': {
    description: "Coin Value Price Chart for Classic Head Large Cents 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Classic Head Large Cents are worth. Buy & Sell. Coins for sale for Classic Head type Large Cents items.",
    designer: "John Reich",
    composition: "100% Copper",
    diameter: "29 mm",
    weight: "10.89 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/classic-head-large-cent.webp",
  },
  'coronet-matron-head-cent': {
    description: "Coin Value Price Chart for Coronet Liberty Head Large Cents 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Coronet Liberty Head Large Cents are worth. Buy & Sell. Coins for sale for Coronet Liberty Head type Large Cents items.",
    designer: "Robert Scot",
    composition: "100% Copper",
    diameter: "28.5 mm",
    weight: "10.89 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/coronet-large-cent.webp",
  },
  'braided-hair-cent': {
    description: "Coin Value Price Chart for Braided Hair Liberty Head Large Cents 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Braided Hair Liberty Head Large Cents are worth. Buy & Sell. Coins for sale for Braided Hair Liberty Head type Large Cents items.",
    designer: "Christian Gobrecht",
    composition: "100% Copper",
    diameter: "28.5 mm",
    weight: "10.89 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/braided-hair-large-cent.webp",
  },
  'flying-eagle-cent': {
    description: "Coin Value Price Chart for Flying Eagle Cent 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Flying Eagle Cent are worth. Buy & Sell. Coins for sale for Flying Eagle Cent type items.",
    designer: "James B Longacre",
    composition: "88% Copper - 12% Nickel",
    diameter: "19 mm",
    weight: "4.67 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/flying-eagle-cent.webp",
    keyDates: [
      "1856 Flying Eagle Cent",
    ],
  },
  'indian-head-cent': {
    description: "Coin Value Price Chart for Indian Head Cent 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Indian Head Cent are worth. Buy & Sell. Coins for sale for Indian Head Cent type items.",
    designer: "James B Longacre",
    composition: "95% Copper - 5% Tin and Zinc",
    diameter: "19 mm",
    weight: "3.11 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/indian-head-cent-laurel-wreath.webp",
  },
  'lincoln-wheat-cent': {
    description: "Coin Value Price Chart for Lincoln Wheat Cent 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Lincoln Wheat Cent are worth. Buy & Sell. Coins for sale for Lincoln Wheat Cent type items.",
    designer: "Victor D Brenner",
    composition: "95% Copper - 5% Tin and Zinc",
    diameter: "19 mm",
    weight: "3.11 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/lincoln-wheat-cent.webp",
    keyDates: [
      "1943 Lincoln Wheat Cent : Bronze/Copper",
      "1943 D Lincoln Wheat Cent : Bronze/Copper",
      "1943 S Lincoln Wheat Cent : Bronze/Copper",
      "1944 Lincoln Wheat Cent : Steel Cent",
      "1944 D Lincoln Wheat Cent : Steel Cent",
      "1944 S Lincoln Wheat Cent : Steel Cent",
      "1958 Lincoln Wheat Cent : Doubled-Die Obverse",
    ],
  },
  'lincoln-memorial-cent': {
    description: "Coin Value Price Chart for Lincoln Memorial Cent 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Lincoln Memorial Cent are worth. Buy & Sell. Coins for sale for Lincoln Memorial Cent type items.",
    designer: "Frank Gasparro",
    composition: "97.5% Zinc - 2.5% Copper after 1982",
    diameter: "19 mm",
    weight: "2.5 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/lincoln-memorial-cent.webp",
  },
  'lincoln-shield-cent': {
    description: "Coin Value Price Chart for Lincoln Shield Cent 1C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Lincoln Shield Cent are worth. Buy & Sell. Coins for sale for Lincoln Shield Cent type items.",
    designer: "Frank Gasparro",
    composition: "97.5% Zinc - 2.5% Copper",
    diameter: "19 mm",
    weight: "2.5 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/lincoln-shield-cent.webp",
  },
  'three-cent-silver': {
    description: "Coin Value Price Chart for Silver Three Cent 3C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Silver Three Cent are worth. Buy & Sell. Coins for sale for Silver Three Cent type items.",
    designer: "James B Longacre",
    composition: "90% Silver - 10% Copper",
    diameter: "14 mm",
    weight: "0.75 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/three-cent-piece-silver-type-1-no-star-outlines.webp",
    keyDates: [
      "1863 Silver Three Cent",
      "1864 Silver Three Cent",
      "1865 Silver Three Cent",
      "1866 Silver Three Cent",
      "1867 Silver Three Cent",
      "1868 Silver Three Cent",
      "1869 Silver Three Cent",
      "1870 Silver Three Cent",
    ],
  },
  'three-cent-nickel': {
    description: "Coin Value Price Chart for Nickel Three Cent 3C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Nickel Three Cent are worth. Buy & Sell. Coins for sale for Nickel Three Cent type items.",
    designer: "James B Longacre",
    composition: "75% Copper - 25% Nickel",
    diameter: "17.9 mm",
    weight: "1.94 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/three-cent-piece-nickel.webp",
    keyDates: [
      "1877 Nickel Three Cent : Proof Only",
      "1878 Nickel Three Cent : Proof Only",
      "1879 Nickel Three Cent",
      "1880 Nickel Three Cent",
      "1882 Nickel Three Cent",
      "1883 Nickel Three Cent",
      "1884 Nickel Three Cent",
      "1885 Nickel Three Cent",
    ],
  },
  'flowing-hair-half-dime': {
    description: "Coin Value Price Chart for Flowing Hair Half Dimes H10C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Flowing Hair Half Dimes are worth. Buy & Sell. Coins for sale for Flowing Hair type Half Dimes items.",
    designer: "Robert Scot",
    composition: "89% Silver - 11% Copper",
    diameter: "16.5 mm",
    weight: "1.34 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/flowing-hair-half-dime.webp",
  },
  'draped-bust-half-dime': {
    description: "Coin Value Price Chart for Draped Bust Half Dimes H10C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Draped Bust Half Dimes are worth. Buy & Sell. Coins for sale for Draped Bust type Half Dimes items.",
    designer: "Robert Scot",
    composition: "89% Silver - 11% Copper",
    diameter: "16.5 mm",
    weight: "1.35 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/draped-bust-half-dime-small-eagle.webp",
    keyDates: [
      "1796 Draped Bust Half Dimes : 6 Over 5",
      "1797 Draped Bust Half Dimes : 15 Stars",
      "1800 Draped Bust Half Dimes",
      "1800 Draped Bust Half Dimes : LIBEKTY",
      "1801 Draped Bust Half Dimes",
      "1802 Draped Bust Half Dimes",
      "1803 Draped Bust Half Dimes : Large 8",
      "1805 Draped Bust Half Dimes",
    ],
  },
  'capped-bust-half-dime': {
    description: "Coin Value Price Chart for Capped Bust Half Dimes H10C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Capped Bust Half Dimes are worth. Buy & Sell. Coins for sale for Capped Bust type Half Dimes items.",
    designer: "William Kneass",
    composition: "89% Silver - 11% Copper",
    diameter: "15.5 mm",
    weight: "1.35 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/capped-liberty-bust-half-dime.webp",
  },
  'liberty-seated-half-dime': {
    description: "Coin Value Price Chart for Seated Liberty Half Dimes H10C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Seated Liberty Half Dimes are worth. Buy & Sell. Coins for sale for Seated Liberty type Half Dimes items.",
    designer: "Christian Gobrecht",
    composition: "90% Silver - 10% Copper",
    diameter: "15.5 mm",
    weight: "1.24 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/seated-liberty-half-dime-type-1-no-stars-around-rim.webp",
    keyDates: [
      "1846 Seated Liberty Half Dimes",
      "1859 Seated Liberty Half Dimes : Obverse of 1859 - Reverse of 1860",
      "1860 Seated Liberty Half Dimes : Obverse of 1859 - Reverse of 1860 - With Stars",
      "1863 Seated Liberty Half Dimes",
      "1864 Seated Liberty Half Dimes",
      "1865 Seated Liberty Half Dimes",
      "1866 Seated Liberty Half Dimes",
      "1867 Seated Liberty Half Dimes",
    ],
  },
  'shield-nickel': {
    description: "Coin Value Price Chart for Shield Nickels 5C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Shield Nickels are worth. Buy & Sell. Coins for sale for Shield type Nickels items.",
    designer: "James B Longacre",
    composition: "75% Copper - 25% Nickel",
    diameter: "20.5 mm",
    weight: "5 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/shield-nickel.webp",
    keyDates: [
      "1877 Shield Nickels : Proof Only",
      "1878 Shield Nickels : Proof Only",
      "1879 Shield Nickels",
      "1880 Shield Nickels",
    ],
  },
  'liberty-head-nickel': {
    description: "Coin Value Price Chart for Liberty Nickels 5C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Liberty Nickels are worth. Buy & Sell. Coins for sale for Liberty type Nickels items.",
    designer: "Charles E Barber",
    composition: "75% Copper - 25% Nickel",
    diameter: "21.2 mm",
    weight: "5 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/liberty-head-nickel.webp",
    keyDates: [
      "1913 Liberty Nickels",
    ],
  },
  'buffalo-nickel': {
    description: "Coin Value Price Chart for Buffalo Nickels 5C. Lookup Coin values for Good, Very Good, Fine, Very Fine, Brilliant Uncirculated & Proof conditions and MS grade. How much Buffalo Nickels are worth. Buy & Sell. Coins for sale for Buffalo type Nickels items.",
    designer: "James Earle Fraser",
    composition: "75% Copper - 25% Nickel",
    diameter: "21.2 mm",
    weight: "5 grams",
    imageUrl: "https://i.usacoinbook.com/us-coins/600/buffalo-nickel-mound-type.webp",
  },
}