// Auto-generated by scripts/generate-from-checkpoint.mjs from USA Coin Book data.

export interface CoinDate {
  year: number
  mintMarks: string[]
}

export interface SeriesDateData {
  name: string
  category: string
  slug: string
  dates: CoinDate[]
}

export const COIN_DATES: Record<string, SeriesDateData> = {
  'half-cents/liberty-cap': {
    name: "Liberty Cap",
    category: "",
    slug: "half-cents/liberty-cap",
    dates: [
      { year: 1793, mintMarks: ["P"] },
      { year: 1794, mintMarks: ["P"] },
      { year: 1795, mintMarks: ["P"] },
      { year: 1796, mintMarks: ["P"] },
      { year: 1797, mintMarks: ["P"] },
    ],
  },
  'half-cents/draped-bust': {
    name: "Draped Bust",
    category: "",
    slug: "half-cents/draped-bust",
    dates: [
      { year: 1800, mintMarks: ["P"] },
      { year: 1802, mintMarks: ["P"] },
      { year: 1803, mintMarks: ["P"] },
      { year: 1804, mintMarks: ["P"] },
      { year: 1805, mintMarks: ["P"] },
      { year: 1806, mintMarks: ["P"] },
      { year: 1807, mintMarks: ["P"] },
      { year: 1808, mintMarks: ["P"] },
    ],
  },
  'half-cents/classic-head': {
    name: "Classic Head",
    category: "",
    slug: "half-cents/classic-head",
    dates: [
      { year: 1809, mintMarks: ["P"] },
      { year: 1810, mintMarks: ["P"] },
      { year: 1811, mintMarks: ["P"] },
      { year: 1825, mintMarks: ["P"] },
      { year: 1826, mintMarks: ["P"] },
      { year: 1828, mintMarks: ["P"] },
      { year: 1829, mintMarks: ["P"] },
      { year: 1831, mintMarks: ["P"] },
      { year: 1832, mintMarks: ["P"] },
      { year: 1833, mintMarks: ["P"] },
      { year: 1834, mintMarks: ["P"] },
      { year: 1835, mintMarks: ["P"] },
      { year: 1836, mintMarks: ["P"] },
    ],
  },
  'half-cents/braided-hair': {
    name: "Braided Hair",
    category: "",
    slug: "half-cents/braided-hair",
    dates: [
      { year: 1840, mintMarks: ["P"] },
      { year: 1841, mintMarks: ["P"] },
      { year: 1842, mintMarks: ["P"] },
      { year: 1843, mintMarks: ["P"] },
      { year: 1844, mintMarks: ["P"] },
      { year: 1845, mintMarks: ["P"] },
      { year: 1846, mintMarks: ["P"] },
      { year: 1847, mintMarks: ["P"] },
      { year: 1848, mintMarks: ["P"] },
      { year: 1849, mintMarks: ["P"] },
      { year: 1850, mintMarks: ["P"] },
      { year: 1851, mintMarks: ["P"] },
      { year: 1852, mintMarks: ["P"] },
      { year: 1853, mintMarks: ["P"] },
      { year: 1854, mintMarks: ["P"] },
      { year: 1855, mintMarks: ["P"] },
      { year: 1856, mintMarks: ["P"] },
      { year: 1857, mintMarks: ["P"] },
    ],
  },
  'large-cents/flowing-hair': {
    name: "Flowing Hair",
    category: "",
    slug: "large-cents/flowing-hair",
    dates: [
      { year: 1793, mintMarks: ["P"] },
    ],
  },
  'large-cents/liberty-cap': {
    name: "Liberty Cap",
    category: "",
    slug: "large-cents/liberty-cap",
    dates: [
      { year: 1793, mintMarks: ["P"] },
      { year: 1794, mintMarks: ["P"] },
      { year: 1795, mintMarks: ["P"] },
      { year: 1796, mintMarks: ["P"] },
    ],
  },
  'large-cents/draped-bust': {
    name: "Draped Bust",
    category: "",
    slug: "large-cents/draped-bust",
    dates: [
      { year: 1796, mintMarks: ["P"] },
      { year: 1797, mintMarks: ["P"] },
      { year: 1798, mintMarks: ["P"] },
      { year: 1799, mintMarks: ["P"] },
      { year: 1800, mintMarks: ["P"] },
      { year: 1801, mintMarks: ["P"] },
      { year: 1802, mintMarks: ["P"] },
      { year: 1803, mintMarks: ["P"] },
      { year: 1804, mintMarks: ["P"] },
      { year: 1805, mintMarks: ["P"] },
      { year: 1806, mintMarks: ["P"] },
      { year: 1807, mintMarks: ["P"] },
    ],
  },
  'large-cents/classic-head': {
    name: "Classic Head",
    category: "",
    slug: "large-cents/classic-head",
    dates: [
      { year: 1808, mintMarks: ["P"] },
      { year: 1809, mintMarks: ["P"] },
      { year: 1810, mintMarks: ["P"] },
      { year: 1811, mintMarks: ["P"] },
      { year: 1812, mintMarks: ["P"] },
      { year: 1813, mintMarks: ["P"] },
      { year: 1814, mintMarks: ["P"] },
    ],
  },
}