/**
 * Generates updated coin-education.ts and coin-dates.ts from full-coin-data.json.
 * Run: node scripts/generate-coin-ts.mjs
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'

const INPUT = 'scripts/full-coin-data.json'
const EDUCATION_OUT = 'src/lib/coins/coin-education.ts'
const DATES_OUT = 'src/lib/coins/coin-dates.ts'

if (!existsSync(INPUT)) {
  console.error(`${INPUT} not found. Run scrape-full.mjs first.`)
  process.exit(1)
}

const data = JSON.parse(readFileSync(INPUT, 'utf8'))

// ── Helpers ───────────────────────────────────────────────────────────────────
function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

function clean(str) {
  if (!str) return ''
  return str
    .replace(/—/g, '-')
    .replace(/\s+/g, ' ')
    .replace(/'/g, "'")
    .trim()
}

// Map USA Coin Book category/series slugs to catalog flat slugs
// USA Coin Book: "half-cents/liberty-cap"
// Catalog: "liberty-cap-half-cent"
function ucbSlugToCatalogSlug(categorySlug, seriesSlug) {
  const seriesPart = seriesSlug.includes('/') ? seriesSlug.split('/').pop() : seriesSlug
  const catPart = categorySlug.replace(/s$/, '') // "half-cents" -> "half-cent"
  return `${seriesPart}-${catPart}`
}

// ── Build education data ──────────────────────────────────────────────────────
function buildEducation(data) {
  const education = {}

  for (const category of data.categories) {
    for (const series of category.series) {
      // Derive flat catalog slug
      const catalogSlug = ucbSlugToCatalogSlug(category.slug, series.slug)

      const entry = {}

      if (series.description) entry.description = clean(series.description)
      if (series.designer) entry.designer = clean(series.designer)
      if (series.composition) entry.composition = clean(series.composition)
      if (series.diameter) entry.diameter = clean(series.diameter)
      if (series.weight) entry.weight = clean(series.weight)
      if (series.edge) entry.edge = clean(series.edge)
      if (series.imageUrl) entry.imageUrl = series.imageUrl

      // Key dates: coins with low mintage or notable varieties
      const keyDates = []
      if (series.coins) {
        const LOW_MINTAGE_THRESHOLD = 50000
        for (const coin of series.coins) {
          const mintage = coin.mintage ? parseInt(coin.mintage.replace(/\D/g, '')) : null
          if (mintage && mintage < LOW_MINTAGE_THRESHOLD && coin.title) {
            keyDates.push(clean(coin.title))
          }
        }
      }
      if (keyDates.length > 0) entry.keyDates = keyDates.slice(0, 8)

      if (Object.keys(entry).length > 0) {
        education[catalogSlug] = entry
      }
    }
  }

  return education
}

// ── Build dates data ──────────────────────────────────────────────────────────
function buildDates(data) {
  const dates = {}

  for (const category of data.categories) {
    for (const series of category.series) {
      if (!series.coins || series.coins.length === 0) continue

      const ucbKey = series.slug // e.g. "half-cents/liberty-cap"

      // Group coins by year + mintmark
      const yearMap = new Map()
      for (const coin of series.coins) {
        if (!coin.year) continue
        const year = coin.year
        if (!yearMap.has(year)) yearMap.set(year, new Set())
        if (coin.mintMark) yearMap.get(year).add(coin.mintMark)
      }

      if (yearMap.size === 0) continue

      const dateEntries = []
      for (const [year, mints] of [...yearMap.entries()].sort((a, b) => a[0] - b[0])) {
        dateEntries.push({
          year,
          mintMarks: [...mints].sort(),
        })
      }

      dates[ucbKey] = {
        name: series.name,
        category: category.name,
        slug: ucbKey,
        dates: dateEntries,
      }
    }
  }

  return dates
}

// ── Generate TypeScript ───────────────────────────────────────────────────────
function serializeEducation(education) {
  const lines = [
    "// Auto-generated by scripts/generate-coin-ts.mjs from USA Coin Book data.",
    "// Do not edit manually.",
    "",
    "export interface CoinEducation {",
    "  description?: string",
    "  designer?: string",
    "  composition?: string",
    "  diameter?: string",
    "  weight?: string",
    "  edge?: string",
    "  imageUrl?: string",
    "  keyDates?: string[]",
    "}",
    "",
    "export const COIN_EDUCATION: Record<string, CoinEducation> = {",
  ]

  for (const [slug, entry] of Object.entries(education)) {
    lines.push(`  '${slug}': {`)
    for (const [key, val] of Object.entries(entry)) {
      if (Array.isArray(val)) {
        lines.push(`    ${key}: [`)
        for (const item of val) {
          lines.push(`      ${JSON.stringify(item)},`)
        }
        lines.push(`    ],`)
      } else {
        lines.push(`    ${key}: ${JSON.stringify(val)},`)
      }
    }
    lines.push(`  },`)
  }

  lines.push("}")
  return lines.join('\n')
}

function serializeDates(dates) {
  const lines = [
    "// Auto-generated by scripts/generate-coin-ts.mjs from USA Coin Book data.",
    "// Do not edit manually.",
    "",
    "export interface CoinDateEntry {",
    "  year: number",
    "  mintMarks: string[]",
    "}",
    "",
    "export interface CoinDateData {",
    "  name: string",
    "  category: string",
    "  slug: string",
    "  dates: CoinDateEntry[]",
    "}",
    "",
    "export const COIN_DATES: Record<string, CoinDateData> = {",
  ]

  for (const [key, val] of Object.entries(dates)) {
    lines.push(`  '${key}': {`)
    lines.push(`    name: ${JSON.stringify(val.name)},`)
    lines.push(`    category: ${JSON.stringify(val.category)},`)
    lines.push(`    slug: ${JSON.stringify(val.slug)},`)
    lines.push(`    dates: [`)
    for (const d of val.dates) {
      lines.push(`      { year: ${d.year}, mintMarks: [${d.mintMarks.map(m => JSON.stringify(m)).join(', ')}] },`)
    }
    lines.push(`    ],`)
    lines.push(`  },`)
  }

  lines.push("}")
  return lines.join('\n')
}

// ── Main ──────────────────────────────────────────────────────────────────────
const education = buildEducation(data)
const dates = buildDates(data)

console.log(`Education entries: ${Object.keys(education).length}`)
console.log(`Date series: ${Object.keys(dates).length}`)

writeFileSync(EDUCATION_OUT, serializeEducation(education))
console.log(`Written ${EDUCATION_OUT}`)

writeFileSync(DATES_OUT, serializeDates(dates))
console.log(`Written ${DATES_OUT}`)

// Print sample
const firstEd = Object.entries(education)[0]
console.log('\nSample education entry:', firstEd[0], JSON.stringify(firstEd[1], null, 2).slice(0, 300))
